; Объявления функций API
extrn __imp_GetOpenFileNameW:QWORD
extrn __imp_GetModuleHandleW:QWORD
extrn __imp_GetStdHandle:QWORD
extrn __imp_WriteConsoleA:QWORD
extrn __imp_ReadConsoleA:QWORD
extrn __imp_wsprintfA:QWORD
extrn __imp_ExitProcess:QWORD
extrn __imp_lstrlenA:QWORD
extrn __imp_CreateFileW:QWORD
extrn __imp_ReadFile:QWORD
extrn __imp_WriteFile:QWORD
extrn __imp_CloseHandle:QWORD
extrn __imp_GetFileSize:QWORD